# Generated by Django 4.2.1 on 2023-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
