# Generated by Django 4.2.1 on 2023-06-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_news_options_alter_person_telephone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Право', 'verbose_name_plural': 'Права'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
