# Generated by Django 4.2.1 on 2023-06-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_person_email_person_first_name_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='news',
            name='new',
            field=models.CharField(max_length=700),
        ),
    ]
